version: '3.9'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: concierge_postgres
    environment:
      POSTGRES_USER: concierge
      POSTGRES_PASSWORD: concierge
      POSTGRES_DB: concierge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concierge"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: concierge_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  postgres_data:
  redis_data:
